/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rd.template.gradle.utilities;

public class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
