/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rd.template.gradle.utilities;

import org.junit.jupiter.api.Test;
import org.rd.template.gradle.utilities.MessageUtils;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MessageUtilsTest {
    @Test
    public void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
